// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB20GS2y47V01QOsL8PuMSWHOVSub_V17w',
    appId: '1:790443014897:web:6930c61b6a8e255eb9c750',
    messagingSenderId: '790443014897',
    projectId: 'final-year-project-c8d9f',
    authDomain: 'final-year-project-c8d9f.firebaseapp.com',
    databaseURL: 'https://final-year-project-c8d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-year-project-c8d9f.appspot.com',
    measurementId: 'G-C37J6PGB7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvR8nr8JT4ydzMAe7eMGonvrdqltT8TiU',
    appId: '1:790443014897:android:4e1c95961f28630ab9c750',
    messagingSenderId: '790443014897',
    projectId: 'final-year-project-c8d9f',
    databaseURL: 'https://final-year-project-c8d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-year-project-c8d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXG09zjZ_6Y88z0XrbAfBv5m6oiwf57Hg',
    appId: '1:790443014897:ios:782359809fc057a8b9c750',
    messagingSenderId: '790443014897',
    projectId: 'final-year-project-c8d9f',
    databaseURL: 'https://final-year-project-c8d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-year-project-c8d9f.appspot.com',
    iosBundleId: 'com.example.myAgriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXG09zjZ_6Y88z0XrbAfBv5m6oiwf57Hg',
    appId: '1:790443014897:ios:a0f1dd1dae4fb347b9c750',
    messagingSenderId: '790443014897',
    projectId: 'final-year-project-c8d9f',
    databaseURL: 'https://final-year-project-c8d9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-year-project-c8d9f.appspot.com',
    iosBundleId: 'com.example.myAgriApp.RunnerTests',
  );
}
