name: my_agri_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  get: ^4.6.6
  connectivity_plus: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
